package com.experian.payline.wsclient;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-30T11:14:07.259+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "DirectPaymentAPI", 
                  wsdlLocation = "WebPaymentAPI-homologation.wsdl",
                  targetNamespace = "http://impl.ws.payline.experian.com") 
public class DirectPaymentAPI_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.payline.experian.com", "DirectPaymentAPI");
    public final static QName DirectPaymentAPI = new QName("http://impl.ws.payline.experian.com", "DirectPaymentAPI");
    static {
        URL url = DirectPaymentAPI_Service.class.getResource("WebPaymentAPI-homologation.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(DirectPaymentAPI_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "WebPaymentAPI-homologation.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public DirectPaymentAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DirectPaymentAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectPaymentAPI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectPaymentAPI_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectPaymentAPI_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DirectPaymentAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DirectPaymentAPI
     */
    @WebEndpoint(name = "DirectPaymentAPI")
    public DirectPaymentAPI getDirectPaymentAPI() {
        return super.getPort(DirectPaymentAPI, DirectPaymentAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectPaymentAPI
     */
    @WebEndpoint(name = "DirectPaymentAPI")
    public DirectPaymentAPI getDirectPaymentAPI(WebServiceFeature... features) {
        return super.getPort(DirectPaymentAPI, DirectPaymentAPI.class, features);
    }

}
