
package com.experian.payline.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-30T11:14:07.209+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class DirectPaymentAPI_DirectPaymentAPI_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.payline.experian.com", "DirectPaymentAPI");

    private DirectPaymentAPI_DirectPaymentAPI_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DirectPaymentAPI_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DirectPaymentAPI_Service ss = new DirectPaymentAPI_Service(wsdlURL, SERVICE_NAME);
        DirectPaymentAPI port = ss.getDirectPaymentAPI();  
        
        {
        System.out.println("Invoking doCapture...");
        DoCaptureRequest _doCapture_parameters = null;
        DoCaptureResponse _doCapture__return = port.doCapture(_doCapture_parameters);
        System.out.println("doCapture.result=" + _doCapture__return);


        }
        {
        System.out.println("Invoking doScheduledWalletPayment...");
        DoScheduledWalletPaymentRequest _doScheduledWalletPayment_parameters = null;
        DoScheduledWalletPaymentResponse _doScheduledWalletPayment__return = port.doScheduledWalletPayment(_doScheduledWalletPayment_parameters);
        System.out.println("doScheduledWalletPayment.result=" + _doScheduledWalletPayment__return);


        }
        {
        System.out.println("Invoking doAuthorization...");
        DoAuthorizationRequest _doAuthorization_parameters = null;
        DoAuthorizationResponse _doAuthorization__return = port.doAuthorization(_doAuthorization_parameters);
        System.out.println("doAuthorization.result=" + _doAuthorization__return);


        }
        {
        System.out.println("Invoking getCards...");
        GetCardsRequest _getCards_parameters = null;
        GetCardsResponse _getCards__return = port.getCards(_getCards_parameters);
        System.out.println("getCards.result=" + _getCards__return);


        }
        {
        System.out.println("Invoking getEncryptionKey...");
        GetEncryptionKeyRequest _getEncryptionKey_parameters = null;
        GetEncryptionKeyResponse _getEncryptionKey__return = port.getEncryptionKey(_getEncryptionKey_parameters);
        System.out.println("getEncryptionKey.result=" + _getEncryptionKey__return);


        }
        {
        System.out.println("Invoking disableWallet...");
        DisableWalletRequest _disableWallet_parameters = null;
        DisableWalletResponse _disableWallet__return = port.disableWallet(_disableWallet_parameters);
        System.out.println("disableWallet.result=" + _disableWallet__return);


        }
        {
        System.out.println("Invoking getBalance...");
        GetBalanceRequest _getBalance_parameters = null;
        GetBalanceResponse _getBalance__return = port.getBalance(_getBalance_parameters);
        System.out.println("getBalance.result=" + _getBalance__return);


        }
        {
        System.out.println("Invoking doRecurrentWalletPayment...");
        DoRecurrentWalletPaymentRequest _doRecurrentWalletPayment_parameters = null;
        DoRecurrentWalletPaymentResponse _doRecurrentWalletPayment__return = port.doRecurrentWalletPayment(_doRecurrentWalletPayment_parameters);
        System.out.println("doRecurrentWalletPayment.result=" + _doRecurrentWalletPayment__return);


        }
        {
        System.out.println("Invoking doReAuthorization...");
        DoReAuthorizationRequest _doReAuthorization_parameters = null;
        DoReAuthorizationResponse _doReAuthorization__return = port.doReAuthorization(_doReAuthorization_parameters);
        System.out.println("doReAuthorization.result=" + _doReAuthorization__return);


        }
        {
        System.out.println("Invoking verifyAuthentication...");
        VerifyAuthenticationRequest _verifyAuthentication_parameters = null;
        VerifyAuthenticationResponse _verifyAuthentication__return = port.verifyAuthentication(_verifyAuthentication_parameters);
        System.out.println("verifyAuthentication.result=" + _verifyAuthentication__return);


        }
        {
        System.out.println("Invoking doScoringCheque...");
        DoScoringChequeRequest _doScoringCheque_parameters = null;
        DoScoringChequeResponse _doScoringCheque__return = port.doScoringCheque(_doScoringCheque_parameters);
        System.out.println("doScoringCheque.result=" + _doScoringCheque__return);


        }
        {
        System.out.println("Invoking createWallet...");
        CreateWalletRequest _createWallet_parameters = null;
        CreateWalletResponse _createWallet__return = port.createWallet(_createWallet_parameters);
        System.out.println("createWallet.result=" + _createWallet__return);


        }
        {
        System.out.println("Invoking doReset...");
        DoResetRequest _doReset_parameters = null;
        DoResetResponse _doReset__return = port.doReset(_doReset_parameters);
        System.out.println("doReset.result=" + _doReset__return);


        }
        {
        System.out.println("Invoking disablePaymentRecord...");
        DisablePaymentRecordRequest _disablePaymentRecord_parameters = null;
        DisablePaymentRecordResponse _disablePaymentRecord__return = port.disablePaymentRecord(_disablePaymentRecord_parameters);
        System.out.println("disablePaymentRecord.result=" + _disablePaymentRecord__return);


        }
        {
        System.out.println("Invoking getMerchantSettings...");
        GetMerchantSettingsRequest _getMerchantSettings_parameters = null;
        GetMerchantSettingsResponse _getMerchantSettings__return = port.getMerchantSettings(_getMerchantSettings_parameters);
        System.out.println("getMerchantSettings.result=" + _getMerchantSettings__return);


        }
        {
        System.out.println("Invoking verifyEnrollment...");
        VerifyEnrollmentRequest _verifyEnrollment_parameters = null;
        VerifyEnrollmentResponse _verifyEnrollment__return = port.verifyEnrollment(_verifyEnrollment_parameters);
        System.out.println("verifyEnrollment.result=" + _verifyEnrollment__return);


        }
        {
        System.out.println("Invoking doImmediateWalletPayment...");
        DoImmediateWalletPaymentRequest _doImmediateWalletPayment_parameters = null;
        DoImmediateWalletPaymentResponse _doImmediateWalletPayment__return = port.doImmediateWalletPayment(_doImmediateWalletPayment_parameters);
        System.out.println("doImmediateWalletPayment.result=" + _doImmediateWalletPayment__return);


        }
        {
        System.out.println("Invoking enableWallet...");
        EnableWalletRequest _enableWallet_parameters = null;
        EnableWalletResponse _enableWallet__return = port.enableWallet(_enableWallet_parameters);
        System.out.println("enableWallet.result=" + _enableWallet__return);


        }
        {
        System.out.println("Invoking getPaymentRecord...");
        GetPaymentRecordRequest _getPaymentRecord_parameters = null;
        GetPaymentRecordResponse _getPaymentRecord__return = port.getPaymentRecord(_getPaymentRecord_parameters);
        System.out.println("getPaymentRecord.result=" + _getPaymentRecord__return);


        }
        {
        System.out.println("Invoking getWallet...");
        GetWalletRequest _getWallet_parameters = null;
        GetWalletResponse _getWallet__return = port.getWallet(_getWallet_parameters);
        System.out.println("getWallet.result=" + _getWallet__return);


        }
        {
        System.out.println("Invoking doDebit...");
        DoDebitRequest _doDebit_parameters = null;
        DoDebitResponse _doDebit__return = port.doDebit(_doDebit_parameters);
        System.out.println("doDebit.result=" + _doDebit__return);


        }
        {
        System.out.println("Invoking updateWallet...");
        UpdateWalletRequest _updateWallet_parameters = null;
        UpdateWalletResponse _updateWallet__return = port.updateWallet(_updateWallet_parameters);
        System.out.println("updateWallet.result=" + _updateWallet__return);


        }
        {
        System.out.println("Invoking doRefund...");
        DoRefundRequest _doRefund_parameters = null;
        DoRefundResponse _doRefund__return = port.doRefund(_doRefund_parameters);
        System.out.println("doRefund.result=" + _doRefund__return);


        }
        {
        System.out.println("Invoking createMerchant...");
        CreateMerchantRequest _createMerchant_parameters = null;
        CreateMerchantResponse _createMerchant__return = port.createMerchant(_createMerchant_parameters);
        System.out.println("createMerchant.result=" + _createMerchant__return);


        }
        {
        System.out.println("Invoking doCredit...");
        DoCreditRequest _doCredit_parameters = null;
        DoCreditResponse _doCredit__return = port.doCredit(_doCredit_parameters);
        System.out.println("doCredit.result=" + _doCredit__return);


        }

        System.exit(0);
    }

}
