package com.experian.payline.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-30T11:14:07.235+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://impl.ws.payline.experian.com", name = "DirectPaymentAPI")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DirectPaymentAPI {

    @WebResult(name = "doCaptureResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doCapture")
    public DoCaptureResponse doCapture(
            @WebParam(partName = "parameters", name = "doCaptureRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoCaptureRequest parameters
    );

    @WebResult(name = "doScheduledWalletPaymentResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doScheduledWalletPayment")
    public DoScheduledWalletPaymentResponse doScheduledWalletPayment(
            @WebParam(partName = "parameters", name = "doScheduledWalletPaymentRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoScheduledWalletPaymentRequest parameters
    );

    @WebResult(name = "doAuthorizationResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doAuthorization")
    public DoAuthorizationResponse doAuthorization(
            @WebParam(partName = "parameters", name = "doAuthorizationRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoAuthorizationRequest parameters
    );

    @WebResult(name = "getCardsResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getCards")
    public GetCardsResponse getCards(
            @WebParam(partName = "parameters", name = "getCardsRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetCardsRequest parameters
    );

    @WebResult(name = "getEncryptionKeyResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getEncryptionKey")
    public GetEncryptionKeyResponse getEncryptionKey(
            @WebParam(partName = "parameters", name = "getEncryptionKeyRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetEncryptionKeyRequest parameters
    );

    @WebResult(name = "disableWalletResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "disableWallet")
    public DisableWalletResponse disableWallet(
            @WebParam(partName = "parameters", name = "disableWalletRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DisableWalletRequest parameters
    );

    @WebResult(name = "getBalanceResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getBalance")
    public GetBalanceResponse getBalance(
            @WebParam(partName = "parameters", name = "getBalanceRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetBalanceRequest parameters
    );

    @WebResult(name = "doRecurrentWalletPaymentResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doRecurrentWalletPayment")
    public DoRecurrentWalletPaymentResponse doRecurrentWalletPayment(
            @WebParam(partName = "parameters", name = "doRecurrentWalletPaymentRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoRecurrentWalletPaymentRequest parameters
    );

    @WebResult(name = "doReAuthorizationResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doReAuthorization")
    public DoReAuthorizationResponse doReAuthorization(
            @WebParam(partName = "parameters", name = "doReAuthorizationRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoReAuthorizationRequest parameters
    );

    @WebResult(name = "verifyAuthenticationResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "verifyAuthentication")
    public VerifyAuthenticationResponse verifyAuthentication(
            @WebParam(partName = "parameters", name = "verifyAuthenticationRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            VerifyAuthenticationRequest parameters
    );

    @WebResult(name = "doScoringChequeResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doScoringCheque")
    public DoScoringChequeResponse doScoringCheque(
            @WebParam(partName = "parameters", name = "doScoringChequeRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoScoringChequeRequest parameters
    );

    @WebResult(name = "createWalletResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "createWallet")
    public CreateWalletResponse createWallet(
            @WebParam(partName = "parameters", name = "createWalletRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            CreateWalletRequest parameters
    );

    @WebResult(name = "doResetResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doReset")
    public DoResetResponse doReset(
            @WebParam(partName = "parameters", name = "doResetRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoResetRequest parameters
    );

    @WebResult(name = "disablePaymentRecordResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "disablePaymentRecord")
    public DisablePaymentRecordResponse disablePaymentRecord(
            @WebParam(partName = "parameters", name = "disablePaymentRecordRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DisablePaymentRecordRequest parameters
    );

    @WebResult(name = "getMerchantSettingsResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getMerchantSettings")
    public GetMerchantSettingsResponse getMerchantSettings(
            @WebParam(partName = "parameters", name = "getMerchantSettingsRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetMerchantSettingsRequest parameters
    );

    @WebResult(name = "verifyEnrollmentResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "verifyEnrollment")
    public VerifyEnrollmentResponse verifyEnrollment(
            @WebParam(partName = "parameters", name = "verifyEnrollmentRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            VerifyEnrollmentRequest parameters
    );

    @WebResult(name = "doImmediateWalletPaymentResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doImmediateWalletPayment")
    public DoImmediateWalletPaymentResponse doImmediateWalletPayment(
            @WebParam(partName = "parameters", name = "doImmediateWalletPaymentRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoImmediateWalletPaymentRequest parameters
    );

    @WebResult(name = "enableWalletResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "enableWallet")
    public EnableWalletResponse enableWallet(
            @WebParam(partName = "parameters", name = "enableWalletRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            EnableWalletRequest parameters
    );

    @WebResult(name = "getPaymentRecordResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getPaymentRecord")
    public GetPaymentRecordResponse getPaymentRecord(
            @WebParam(partName = "parameters", name = "getPaymentRecordRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetPaymentRecordRequest parameters
    );

    @WebResult(name = "getWalletResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "getWallet")
    public GetWalletResponse getWallet(
            @WebParam(partName = "parameters", name = "getWalletRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            GetWalletRequest parameters
    );

    @WebResult(name = "doDebitResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doDebit")
    public DoDebitResponse doDebit(
            @WebParam(partName = "parameters", name = "doDebitRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoDebitRequest parameters
    );

    @WebResult(name = "updateWalletResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "updateWallet")
    public UpdateWalletResponse updateWallet(
            @WebParam(partName = "parameters", name = "updateWalletRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            UpdateWalletRequest parameters
    );

    @WebResult(name = "doRefundResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doRefund")
    public DoRefundResponse doRefund(
            @WebParam(partName = "parameters", name = "doRefundRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoRefundRequest parameters
    );

    @WebResult(name = "createMerchantResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "createMerchant")
    public CreateMerchantResponse createMerchant(
            @WebParam(partName = "parameters", name = "createMerchantRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            CreateMerchantRequest parameters
    );

    @WebResult(name = "doCreditResponse", targetNamespace = "http://impl.ws.payline.experian.com", partName = "parameters")
    @WebMethod(action = "doCredit")
    public DoCreditResponse doCredit(
            @WebParam(partName = "parameters", name = "doCreditRequest", targetNamespace = "http://impl.ws.payline.experian.com")
            DoCreditRequest parameters
    );
}
