
package com.experian.payline.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */


import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-30T11:14:07.189+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class WebPaymentAPI_WebPaymentAPI_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.payline.experian.com", "WebPaymentAPI");

    private WebPaymentAPI_WebPaymentAPI_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WebPaymentAPI_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebPaymentAPI_Service ss = new WebPaymentAPI_Service(wsdlURL, SERVICE_NAME);
        WebPaymentAPI port = ss.getWebPaymentAPI();  
		((BindingProvider)port).getRequestContext().put("javax.xml.ws.security.auth.username", "A");
		((BindingProvider)port).getRequestContext().put("javax.xml.ws.security.auth.password", "A");
		((BindingProvider)port).getRequestContext().put("javax.xml.ws.service.endpoint.address", "https://homologation.payline.com/V4/services/WebPaymentAPI");

        {
        System.out.println("Invoking getWebPaymentDetails...");
        GetWebPaymentDetailsRequest _getWebPaymentDetails_parameters = null;
        GetWebPaymentDetailsResponse _getWebPaymentDetails__return = port.getWebPaymentDetails(_getWebPaymentDetails_parameters);
        System.out.println("getWebPaymentDetails.result=" + _getWebPaymentDetails__return);


        }
        {
        System.out.println("Invoking createWebWallet...");
        CreateWebWalletRequest _createWebWallet_parameters = null;
        CreateWebWalletResponse _createWebWallet__return = port.createWebWallet(_createWebWallet_parameters);
        System.out.println("createWebWallet.result=" + _createWebWallet__return);


        }
        {
        System.out.println("Invoking doWebPayment...");
        DoWebPaymentRequest _doWebPayment_parameters = null;
        DoWebPaymentResponse _doWebPayment__return = port.doWebPayment(_doWebPayment_parameters);
        System.out.println("doWebPayment.result=" + _doWebPayment__return);


        }
        {
        System.out.println("Invoking getWebWallet...");
        GetWebWalletRequest _getWebWallet_parameters = null;
        GetWebWalletResponse _getWebWallet__return = port.getWebWallet(_getWebWallet_parameters);
        System.out.println("getWebWallet.result=" + _getWebWallet__return);


        }
        {
        System.out.println("Invoking updateWebWallet...");
        UpdateWebWalletRequest _updateWebWallet_parameters = null;
        UpdateWebWalletResponse _updateWebWallet__return = port.updateWebWallet(_updateWebWallet_parameters);
        System.out.println("updateWebWallet.result=" + _updateWebWallet__return);


        }

        System.exit(0);
    }

}
