
package com.lyra.vads.ws3ds.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-22T22:03:56.288+02:00
 * Generated source version: 2.7.2
 * 
 */
public final class ThreeDSecure_ThreeDSecureServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://threedsecure.ws.vads.lyra.com/", "ThreeDSecure");

    private ThreeDSecure_ThreeDSecureServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ThreeDSecure_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ThreeDSecure_Service ss = new ThreeDSecure_Service(wsdlURL, SERVICE_NAME);
        ThreeDSecure port = ss.getThreeDSecureServicePort();  
        
        {
        System.out.println("Invoking sendVEReqAndbuildPAReqTx...");
        String _sendVEReqAndbuildPAReqTx_shopId = "";
        String _sendVEReqAndbuildPAReqTx_contractNumber = "";
        String _sendVEReqAndbuildPAReqTx_ctxMode = "";
        String _sendVEReqAndbuildPAReqTx_cardNumber = "";
        String _sendVEReqAndbuildPAReqTx_browserUserAgent = "";
        String _sendVEReqAndbuildPAReqTx_browserAccept = "";
        String _sendVEReqAndbuildPAReqTx_purchaseAmount = "";
        String _sendVEReqAndbuildPAReqTx_purchaseCurrency = "";
        String _sendVEReqAndbuildPAReqTx_cardExpiry = "";
        String _sendVEReqAndbuildPAReqTx_wsSignature = "";
        VeResPAReqInfo _sendVEReqAndbuildPAReqTx__return = port.sendVEReqAndbuildPAReqTx(_sendVEReqAndbuildPAReqTx_shopId, _sendVEReqAndbuildPAReqTx_contractNumber, _sendVEReqAndbuildPAReqTx_ctxMode, _sendVEReqAndbuildPAReqTx_cardNumber, _sendVEReqAndbuildPAReqTx_browserUserAgent, _sendVEReqAndbuildPAReqTx_browserAccept, _sendVEReqAndbuildPAReqTx_purchaseAmount, _sendVEReqAndbuildPAReqTx_purchaseCurrency, _sendVEReqAndbuildPAReqTx_cardExpiry, _sendVEReqAndbuildPAReqTx_wsSignature);
        System.out.println("sendVEReqAndbuildPAReqTx.result=" + _sendVEReqAndbuildPAReqTx__return);


        }
        {
        System.out.println("Invoking sendVEReqAndbuildPAReqByIdentifierTx...");
        String _sendVEReqAndbuildPAReqByIdentifierTx_shopId = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_contractNumber = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_ctxMode = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_identifier = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_browserUserAgent = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_browserAccept = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_purchaseAmount = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_purchaseCurrency = "";
        String _sendVEReqAndbuildPAReqByIdentifierTx_wsSignature = "";
        VeResPAReqInfo _sendVEReqAndbuildPAReqByIdentifierTx__return = port.sendVEReqAndbuildPAReqByIdentifierTx(_sendVEReqAndbuildPAReqByIdentifierTx_shopId, _sendVEReqAndbuildPAReqByIdentifierTx_contractNumber, _sendVEReqAndbuildPAReqByIdentifierTx_ctxMode, _sendVEReqAndbuildPAReqByIdentifierTx_identifier, _sendVEReqAndbuildPAReqByIdentifierTx_browserUserAgent, _sendVEReqAndbuildPAReqByIdentifierTx_browserAccept, _sendVEReqAndbuildPAReqByIdentifierTx_purchaseAmount, _sendVEReqAndbuildPAReqByIdentifierTx_purchaseCurrency, _sendVEReqAndbuildPAReqByIdentifierTx_wsSignature);
        System.out.println("sendVEReqAndbuildPAReqByIdentifierTx.result=" + _sendVEReqAndbuildPAReqByIdentifierTx__return);


        }
        {
        System.out.println("Invoking analyzePAResTx...");
        String _analyzePAResTx_shopId = "";
        String _analyzePAResTx_contractNumber = "";
        String _analyzePAResTx_ctxMode = "";
        String _analyzePAResTx_requestId = "";
        String _analyzePAResTx_pares = "";
        String _analyzePAResTx_wsSignature = "";
        PaResInfo _analyzePAResTx__return = port.analyzePAResTx(_analyzePAResTx_shopId, _analyzePAResTx_contractNumber, _analyzePAResTx_ctxMode, _analyzePAResTx_requestId, _analyzePAResTx_pares, _analyzePAResTx_wsSignature);
        System.out.println("analyzePAResTx.result=" + _analyzePAResTx__return);


        }

        System.exit(0);
    }

}
