package com.lyra.vads.ws3ds.stub;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2013-05-22T22:03:56.341+02:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "ThreeDSecure", 
                  wsdlLocation = "SystemPay_3DSecure.wsdl",
                  targetNamespace = "http://threedsecure.ws.vads.lyra.com/") 
public class ThreeDSecure_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://threedsecure.ws.vads.lyra.com/", "ThreeDSecure");
    public final static QName ThreeDSecureServicePort = new QName("http://threedsecure.ws.vads.lyra.com/", "ThreeDSecureServicePort");
    static {
        URL url = ThreeDSecure_Service.class.getResource("SystemPay_3DSecure.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ThreeDSecure_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "SystemPay_3DSecure.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ThreeDSecure_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ThreeDSecure_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ThreeDSecure_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ThreeDSecure_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ThreeDSecure_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ThreeDSecure_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ThreeDSecure
     */
    @WebEndpoint(name = "ThreeDSecureServicePort")
    public ThreeDSecure getThreeDSecureServicePort() {
        return super.getPort(ThreeDSecureServicePort, ThreeDSecure.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThreeDSecure
     */
    @WebEndpoint(name = "ThreeDSecureServicePort")
    public ThreeDSecure getThreeDSecureServicePort(WebServiceFeature... features) {
        return super.getPort(ThreeDSecureServicePort, ThreeDSecure.class, features);
    }

}
