package com.experian.payline.ws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2013-06-27T11:13:23.835+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "DirectPaymentAPI", 
                  wsdlLocation = "file:/Users/hayssams/git/mogopay-core/mogopay/src/java/wsdl/Payline_DirectPaymentAPI.wsdl",
                  targetNamespace = "http://impl.ws.payline.experian.com") 
public class DirectPaymentAPI_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.payline.experian.com", "DirectPaymentAPI");
    public final static QName DirectPaymentAPI = new QName("http://impl.ws.payline.experian.com", "DirectPaymentAPI");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/hayssams/git/mogopay-core/mogopay/src/java/wsdl/Payline_DirectPaymentAPI.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DirectPaymentAPI_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/hayssams/git/mogopay-core/mogopay/src/java/wsdl/Payline_DirectPaymentAPI.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DirectPaymentAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DirectPaymentAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DirectPaymentAPI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DirectPaymentAPI
     */
    @WebEndpoint(name = "DirectPaymentAPI")
    public DirectPaymentAPI getDirectPaymentAPI() {
        return super.getPort(DirectPaymentAPI, DirectPaymentAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DirectPaymentAPI
     */
    @WebEndpoint(name = "DirectPaymentAPI")
    public DirectPaymentAPI getDirectPaymentAPI(WebServiceFeature... features) {
        return super.getPort(DirectPaymentAPI, DirectPaymentAPI.class, features);
    }

}
